### ISSUE TITLE
better link detection

### ISSUE THREAD

**Issue by codeperfectplus** [BaseMax/LinkRemoverTelegramBot#2]
Regex can detect better.

**Comment by IRGC** [comment]
yes

**Comment by IRGC** [comment]
@BaseMax add regex pattern to detect url.

**Comment by BaseMax** [comment]
Thank you for reporting.

@codePerfectPlus It's easy if you want to do it. I can assign this issue to you.

Thanks.

**Comment by codeperfectplus** [comment]
@BaseMax happy to be helpful

**Comment by BaseMax** [comment]
> @BaseMax happy to be helpful

Hi Deepak, Are you working on this issue? Just want to make sure you agree to it or not. Don't worry about it. @codePerfectPlus

**Comment by codeperfectplus** [comment]
Yup, I will be working on it. I will create a PR

**Comment by BaseMax** [comment]
Hi sir, Any updates? @codeperfectplus

**Comment by codeperfectplus** [comment]
I will update after checking the code. 😊
