### ISSUE TITLE
Doesn't delete edited posts with link

### ISSUE THREAD

**Issue by mkay09** [BaseMax/LinkRemoverTelegramBot#4]
I MADE A MISTAKE. IT IS WORKING PERFECTLY. SORRY!

Hey guys, bot is not deleting edited post with a link. For example: When I post "test" into a group channel and edit it into "test google.com" the post is not deleted by the bot.

**Comment by BaseMax** [comment]
I'll check it next week, I'm busy now, I'll provide more functionality or features as you mentioned.

Glad to see it was useful to you.
thanks

**Comment by mkay09** [comment]
Thanks, it works. I just made a mistake 😂

BTW great bot

Max Base ***@***.***> schrieb am So., 1. Sept. 2024, 15:08:

**Comment by BaseMax** [comment]
Okay well, so there is no such issues in the bot/script.

Thanks again!
